# Generated by Django 5.1.1 on 2025-02-08 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("projects", "0002_usefulelementsforproject_aquired_projectinverstors"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="received_by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payments",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.projectinverstors",
            ),
        ),
    ]
