# Generated by Django 5.1.1 on 2025-02-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payments_received_by_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
