# Generated by Django 5.1.1 on 2025-02-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_usefulelementsforproject_aquired_projectinverstors"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinverstors",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
