# Generated by Django 5.1.1 on 2025-02-09 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_role_alter_projectinverstors_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customnotification",
            old_name="message",
            new_name="body",
        ),
        migrations.AddField(
            model_name="customnotification",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
