# Generated by Django 5.1.1 on 2025-02-10 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectinverstors_status_projectjoinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodificationhistory",
            name="modification_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projectfinancement",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="projectmodificationhistory",
            name="new_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmodificationhistory",
            name="old_value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
